apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-ai-react
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LeeKukHyeon/k8s-ai-react-deploy
    targetRevision: main
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: react
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
